import { PrismaClient, UserRole } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Clean existing data
  await prisma.user.deleteMany();

  console.log('🗑️ Cleaned users table');

  // ----------------------
  // USERS (with UUID - auto-generated by Prisma)
  // ----------------------
  const hashed = {
    admin: await bcrypt.hash('Admin123!', 10),
    commercial1: await bcrypt.hash('Commercial123!', 10),
    commercial2: await bcrypt.hash('Commercial456!', 10),
  };

  await prisma.user.createMany({
    data: [
      {
        email: 'admin@company.com',
        password: hashed.admin,
        role: UserRole.ADMIN,
        firstName: 'Admin',
        lastName: 'User',
        telephone: '+212 6 00 00 00 00',
        cin: 'AA123456',
      },
    ],
  });

  const users = await prisma.user.findMany();
  console.log(`👥 Created ${users.length} users:`);
  users.forEach((user) => {
    console.log(`   - ${user.email} (${user.role}) [ID: ${user.id}]`);
  });

  console.log('✅ Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
